### PR TITLE
update from original

### PR DESCRIPTION
**Pull request by virusvfv**

### CODE REVIEW

**Comment by Cyb3rC3lt** [comment]
Hey, I was just looking at testing out the Cloudflare fronting which would be an amazing feature but I struggled to get it working. Same with self-cert too. Any ideas?

image
image

That aside in CloudFlare what protocol do you then map to the ligolo server, is it a raw tcp it is running on?

image

Thanks

**Comment by virusvfv** [comment]
Hi.
Proxy must starts with https:// prefix to instruct server listen https websocket protocol.
-laddr https://0.0.0.0:443
Additionaly U have to make correct cloudflare settings
(https to https)

**Comment by Cyb3rC3lt** [comment]
Legend, got it working. This is very very cool

**Comment by Cyb3rC3lt** [comment]
Can I just ask if it is expected to work with autocert also as I am getting the below? 

image
image

Or is the idea that this isn't required now as it is https to the Cloudflare tunnel then the tunnel securely delivers the data? 
Thanks

**Comment by Cyb3rC3lt** [comment]
Hey @virusvfv, I have been loving using your branch, it is really amazing to use Ligolo with Cloudflare. I have tried to point your ligolo agent at a Cloudflare worker which I could use as a redirector but I get this error in the worker logs. Any ideas why please?

it's like the Cloudflare workers consume the mesages differently to a tunnel.

image

**Comment by virusvfv** [comment]
Hi. I never used CF workers with ligolo, so I can't say anything usefull abour this.
I think that you use standart workers against websocket protocol (ligolo uses websocket to connecting) so CF gives you this error. 
If U want to terminate (parse) ligolo Connection, you have to use websocket workers with CF. See accourding docs from cloudflare about it.

**Comment by Cyb3rC3lt** [comment]
Thanks for the info, much appreciated

**Comment by Cyb3rC3lt** [comment]
Got a cloudflare worker to actually use your agent 😊. That -ua flag is soooo handy! I can send a custom user agent then use the worker to only let the ligolo traffic with that custom user agent into my tunnel. All thanks to you 👍🏻

**Pull request merged**
